#!/usr/bin/env bash

set -a

[[ -f /etc/docker.env ]] && source /etc/docker.env

# avahi-resolve doesn't return non-zero error code on failure :/
for host in $(env \
  | grep -E "^[A-Z0-9_]+_HOST=.*\.${MDNS_TLD}$|^[A-Z0-9_]+_HOSTNAME=.*\.${MDNS_TLD}$" \
  | grep -Ev 'BALENA|files\.' \
  | sed 's|http.*://||g'); do
    avahi-resolve -n4 $(echo ${host} | awk -F'=' '{print $2}') 2>&1 | grep -vE 'Failed|Timeout' || exit $?
done

haproxy="$(ip route get 8.8.8.8 | head -1 | awk '{print $7}'):443"

if [[ -s ${NODE_EXTRA_CA_CERTS} ]]; then
    # ensures self-signed certificates are installed correctly (if any)
    true | openssl s_client -connect "${haproxy}" \
      -servername "${API_HOST}" \
      -CAfile "${NODE_EXTRA_CA_CERTS}"
else
    # public DNS configuration (e.g. LetsEncrypt)
    true | openssl s_client -connect "${haproxy}" -servername "${API_HOST}"
fi
