name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    # FIXME: inherit when GitHub Enterprise ships
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_REGISTRY_PASS }}
      DOCKERHUB_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      FLOWZONE_TOKEN: ${{ secrets.FLOWZONE_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    with:
      docker_images: balena/balena-mdns-publisher
